server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: ia-service
          uri: lb://ia-service
          predicates:
            - Path=/ia/**
        
        - id: mcp-interno
          uri: lb://MCP-INTERNO
          predicates:
            - Path=/mcp/**