server:
  port: 8081

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      show-components: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/

spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: gemma3n
      embedding:
        options:
          model: nomic-embed-text
      client:
        default-options:
          read-timeout: 600

resilience4j:
  retry:
    instances:
      iaServiceCircuitBreaker:
        maxAttempts: 3
        waitDuration: 200ms
  bulkhead:
    instances:
      iaServiceCircuitBreaker:
        maxConcurrentCalls: 10
  ratelimiter:
    instances:
      iaServiceCircuitBreaker:
        limitForPeriod: 5
        limitRefreshPeriod:
  circuitbreaker:
    instances:
      iaServiceCircuitBreaker:
        registerHealthIndicator: true 
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10 # Número de chamadas para observar
        failureRateThreshold: 50 # Porcentagem de falhas para abrir o circuito (50%)
        waitDurationInOpenState: 5000 # Tempo em ms para esperar antes de ir para HALF_OPEN
        permittedNumberOfCallsInHalfOpenState: 3 # Número de chamadas de teste em HALF_OPEN
        automaticTransitionFromOpenToHalfOpenEnabled: true